### ISSUE TITLE
Refactor the builder to support image building overlays

### ISSUE THREAD

**Issue by shuhaowu** [ros-realtime/ros-realtime-rpi4-image#16]
Required for #7 

A few things that needs to be done:

1. Standardize the script names and the paths (like the `rootfs` directory).
2. Right now the builder is called via `sudo ./builder/main.sh focal-ros2-rt/vars.sh`. The idea is to change it so we can call: `sudo ./builder/main.sh focal-rt-base ros-galactic custom-stuff`, where each argument is a directory. The builder then applies the rootfs and scripts in order, allowing for some sort of overlay. Not sure if this will be the final structure, I have to experiment with the code a little bit to make sure it is not spaghetti. 

A minor thing to consider:

1. Consider changing CI such that it only builds when build scripts get changed and not when READMEs gets changed to conserve Github actions limit.

After that, we can re-evaluate and see if we can do some additional longer term improvements (**so not for now**):

1. Make the builder runnable from any directory, so one can bring their own custom overlay. This likely requires replacing the current Makefile with some sort of python program.

cc: @LanderU @carlossvg

**Comment by shuhaowu** [comment]
I looked at this task a bit today. The bash script approach might not work that well with the objectives outlined here as it is a bit too brittle. I'm worried of sinking my (limited) time on an approach that will not scale and be frustrating to debug.

I'm going to briefly investigate turning the `builder/` into Python (some shell scripts will remain, like the phase1 phase2 scripts as they are responsible for installing stuff) to see how easy it is. It shouldn't be too hard and that might be a bit more maintainable and approachable. So it will take a bit more time (hopefully in the next few weeks).

**Comment by carlossvg** [comment]
>I'm going to briefly investigate turning the builder/ into Python (some shell scripts will remain, like the phase1 phase2 scripts as they are responsible for installing stuff) to see how easy it is. It shouldn't be too hard and that might be a bit more maintainable and approachable. So it will take a bit more time (hopefully in the next few weeks).

Sounds good to me
