### ISSUE TITLE
Prepare release

### ISSUE THREAD

**Issue by carlossvg** [ros-realtime/ros-realtime-rpi4-image#20]
Once we consider the project is ready, we will do an official release. Here is a list of things we are considering doing for the official release. 

- [x] Create new release tag and host the image here => https://github.com/ros-realtime/ros-realtime-rpi4-image/releases
- [x] Create one or several tutorials that we can refer to in order to show how the image and the tools work
- [ ] Update Real-Time Linux guides => https://real-time-working-group.readthedocs.io/en/latest/Guides/Real-Time-Operating-System-Setup/Real-Time-Linux/rt_linux_index.html#real-time-linux
- [x] Create https://discourse.ros.org/ announcement
- [x] Discuss how we can further popularize this work: ROSCon talk, ROSCon workshop talk, add references in ROS 2 docs, etc
- [ ] Add image hash for integrity

**Comment by shuhaowu** [comment]
Lightning talk at ROSCon might be a good idea?

**Comment by carlossvg** [comment]
> Lightning talk at ROSCon might be a good idea?

Sounds good to me

**Comment by carlossvg** [comment]
I created a discussion for the release here: https://github.com/ros-realtime/ros-realtime-rpi4-image/discussions/21

**Comment by carlossvg** [comment]
@shuhaowu Is there anything left to do? Wen can support with it needed

**Comment by shuhaowu** [comment]
The release here is done. In two weeks, I'll present it in ROScon 2022 in Tokyo. Should we do anything else? Add it to the documentation? 

Maybe post in ROS discourse? But maybe Discourse can wait until after the ROScon talk?

**Comment by shuhaowu** [comment]
A tutorial exists in the README as well now, but we don't show off the tools anywhere (not sure if it belongs here anyway).
