### ISSUE TITLE
20.04.3 img url is no longer valid

### ISSUE THREAD

**Issue by VTProDesign** [ros-realtime/ros-realtime-rpi4-image#24]
IMAGE_URL="https://cdimage.ubuntu.com/releases/20.04.3/release/ubuntu-20.04.3-preinstalled-server-arm64+raspi.img.xz"

Suggested url:

https://old-releases.ubuntu.com/releases/focal/ubuntu-20.04.3-preinstalled-server-arm64+raspi.img.xz

**Comment by shuhaowu** [comment]
We're aware of this issue. I have a comprehensive refactor coming in #23 that will address this. I'll close it after we merge that PR.

**Comment by LanderU** [comment]
@VTProDesign, thanks a lot for the issue!

You've also the image built here: https://github.com/ros-realtime/ros-realtime-rpi4-image/releases

**Comment by shuhaowu** [comment]
This has been fixed in #23.
