### ISSUE TITLE
Ubuntu 22.04 version of the RPI4 image

### ISSUE THREAD

**Issue by FelixvdDonk** [ros-realtime/ros-realtime-rpi4-image#40]
Hi,

I am assuming ubuntu 20.04 is currently used for the rpi4 image
In this post the ubuntu devs explain how interacting with the GPIO pins has changed since 21.04:
https://ubuntu.com/tutorials/gpio-on-raspberry-pi#1-overview

I'd like to use 22.04 going forward so I don't have to rewrite my code which uses GPIO pins. Is 22.04 already currently being looked at?

**Comment by shuhaowu** [comment]
This issue is blocked by https://github.com/ros-realtime/linux-real-time-kernel-builder/issues/36.

We are all pretty busy but presumably will look into this over the next little while.
