### ISSUE TITLE
Humble release tag is incorrect

### ISSUE THREAD

**Issue by shuhaowu** [ros-realtime/ros-realtime-rpi4-image#46]
I noticed the humble release tag is tagged to a point before we merged the humble build scripts. We should probably fix it with the "final" release.

cc: @LanderU @carlossvg

**Comment by carlossvg** [comment]
@shuhaowu I'm creating the image again. What is the correct tag? Also, can we print a summary of Ubuntu, ROS, LTTNG,  and kernel version when the image generation completes?

**Comment by carlossvg** [comment]
@shuhaowu I see that you are already doing that somehow. Maybe we can simply pretty print it at the end.

**Comment by carlossvg** [comment]
@shuhaowu I created a new tag and added it to the release

**Comment by shuhaowu** [comment]
Oh my original issue was that the tag is pointed at a commit before we merged the PR that introduced humble support. I was thinking of fixing that. What you have is probably fine enough for now. That said, we probably need a standard tag name with the kernel version and the ubuntu version? Maybe something like `ubuntu_<22.04>_<uname -r>_ros2_humble_rpi4`? This way it can be consistent from release to release?
