### ISSUE TITLE
Cannot connect to 5G WiFi

### ISSUE THREAD

**Issue by Oct19** [ros-realtime/ros-realtime-rpi4-image#61]
Hi,
I was running the official Raspberry Pi OS on my Raspberry Pi 400, and it can connect to 5G WiFi. However, after switching to ros-realtime-rpi4-image, it can only connect to 2.4G WiFi. Moreover, after I install ubuntu-desktop, it could not find WiFi adapter.

**Comment by shuhaowu** [comment]
I don't have this issue. The 5ghz WiFi works fine for me.

**Comment by Oct19** [comment]
> I don't have this issue. The 5ghz WiFi works fine for me.

Is it suggested to use Raspberry Pi Imager to config username, hostname, ssh, and WIFI when writing to SD card? Will it overwrite the default 'ubuntu' username and hostname?

**Comment by shuhaowu** [comment]
No. Those settings only work for the raspberry pi os. The WiFi setup documentation is linked in this project's readme

**Comment by Oct19** [comment]
Thanks. It would be good to warn future users not to use Raspberry Pi Imager to play with those settings.

**Comment by Oct19** [comment]
Hi, I found out why I was not able to connect to 5Ghz wifi. Turns out I have to specify my region in /etc/default/crda
