### ISSUE TITLE
Raspberry Pi 3

### ISSUE THREAD

**Issue by brean** [ros-realtime/ros-realtime-rpi4-image#62]
Hi,

I was wondering if it is possible to also build the rt-image for Raspberry Pi 3?
Running ROS 2 humble based on ubuntu 22.04 server seems to work very well although its not fully supported for the rpi 3 (especially with a faster ssd and a some swap).

**Comment by razr** [comment]
have you tried to run this image? It is [stated](https://ubuntu.com/download/raspberry-pi) by Ubuntu that it works on the 2, 3, and 4.

**Comment by mataruzz** [comment]
Yes. I run this image and I immediately saw the improvement in real time.

Thank you!!

**Comment by LanderU** [comment]
I think this is answered here: https://github.com/ros-realtime/ros-realtime-rpi4-image/issues/70
