### ISSUE TITLE
Choose ROS 2 distro deployed on the image

### ISSUE THREAD

**Issue by LanderU** [ros-realtime/ros-realtime-rpi4-image#7]
## Motivation

Right now, we're only installing ROS 2 galactic, we should be able to install any ROS 2 distro available for focal.

## Acceptance Criteria

* [ ] Parametrized the image
* [ ] Check if other ROS 2 versions works properly

**Comment by carlossvg** [comment]
@LanderU @shuhaowu I would parametrize RPI3 and RPI4. For the moment I would default the option to RPI4 and I would leave RPI3 option unimplemented. I would do it as part of the same PR so we define what are the input parameters and what is the expected naming we will use for the releases:

What do you think?

**Comment by shuhaowu** [comment]
That sounds good. Do you need any assistance in making the builder parameterizable? I'm not sure what state I left it in :sweat_smile:

**Comment by LanderU** [comment]
@shuhaowu, I'll try to do it and will ping you for the review :)

**Comment by carlossvg** [comment]
Done here: https://github.com/ros-realtime/ros-realtime-rpi4-image/pull/42
