### ISSUE TITLE
Real time with new user "x"

### ISSUE THREAD

**Issue by mataruzz** [ros-realtime/ros-realtime-rpi4-image#70]
Hello,
I'm using your real time patch on my Raspberry 3B+. The installation didn't give me any problem.

The problem came when I tried to create a new user "x". Now, I'm not able to access to the gpio pins anymore. Get the privilege to access the pins is not a big deal, if not that when running my scripts with user "x" the real time is not happening anymore. It does happened only if I enter in sudo mode (e.g, sudo -s).

How can I set the new user "x" to be set similar as the sudo, giving at least the possibility to work in real time?

Thank you

**Comment by shuhaowu** [comment]
This is likely because you didn't add the user to the appropriate groups. Check out [this article](https://wiki.debian.org/SystemGroups#Groups_without_an_associated_user). It applies to Debian which is probably the same as Ubuntu.

This is not an issue with the image.

**Comment by shuhaowu** [comment]
Also keep in mind that only the ubuntu user (and root of course) is setup with real time permissions. You'll have to repeat that for your own user if you want another user.

**Comment by mataruzz** [comment]
Ok, thank you. Do you know any reference link I can follow to setup the new user with real time permission?

**Comment by LanderU** [comment]
Or add your user to ubuntu group.

**Comment by mataruzz** [comment]
Thank you so much for you quick answer. The security limit config file was exactly what I was looking for.
