### ISSUE TITLE
Turn off memory compaction

### ISSUE THREAD

**Issue by shuhaowu** [ros-realtime/ros-realtime-rpi4-image#71]
I noticed the real-time linux documentation are being changed over the last week and this has appeared on https://wiki.linuxfoundation.org/realtime/documentation/known_limitations

![image](https://github.com/ros-realtime/ros-realtime-rpi4-image/assets/338100/b89cf2a1-5809-4378-8b77-f135b5f9e462)

We should do this as well.

**Comment by LanderU** [comment]
@shuhaowu, do we need to update the kernel config or only apply that on the user-space? I'll open an MR on this to apply that.

**Comment by shuhaowu** [comment]
Should be similar to how we turn off real-time throttling. In fact you can extend that service https://github.com/ros-realtime/ros-realtime-rpi4-image/blob/master/image_builder/data/jammy-rt/rootfs/opt/ros2-rt-rpi4/rt-throttling
